# Generated by Django 3.2.5 on 2021-08-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210804_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='oauth_first_migrate',
            field=models.BooleanField(default=False),
        ),
    ]
