# Generated by Django 3.2.5 on 2021-08-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_oauth_first_migrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='discord',
            field=models.TextField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.TextField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.TextField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='occupation',
            field=models.TextField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.TextField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.URLField(default=''),
        ),
    ]
