# Generated by Django 3.2.5 on 2021-08-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210807_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='osu_username',
            field=models.CharField(default='', max_length=20),
        ),
    ]
