# Generated by Django 3.2.5 on 2021-08-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_profile_osu_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='osu_id',
            field=models.IntegerField(default=0),
        ),
    ]
