# Generated by Django 3.2.5 on 2021-08-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_profile_osu_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='social_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='osu_id',
            field=models.IntegerField(default=''),
        ),
    ]
