# Generated by Django 3.2.5 on 2021-08-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210807_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='update_profile_every_login',
            field=models.BooleanField(default=False),
        ),
    ]
