# Generated by Django 3.2.5 on 2021-08-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_config_update_profile_every_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='osu_id',
            field=models.IntegerField(default=0),
        ),
    ]
