# Generated by Django 3.2.5 on 2021-08-11 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20210811_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='discord',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='osu_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='social_account',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='website',
        ),
    ]
