# Generated by Django 3.2.5 on 2021-08-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20210811_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='theme',
            field=models.TextField(choices=[('', 'Dark Mode (Default)'), ('light', 'Light Mode'), ('sync', 'Sync With System Settings')], default=''),
        ),
    ]
