# Generated by Django 3.2.5 on 2021-08-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_config_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='theme',
            field=models.TextField(choices=[('', 'Dark Mode (Default)'), ('light', 'Light Mode')], default=''),
        ),
    ]
