# Generated by Django 3.2.6 on 2021-08-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_config_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='subpage_index',
            field=models.TextField(choices=[('list', 'List with expandable accordance'), ('button', 'Button')], default='button'),
        ),
    ]
