# Generated by Django 3.2.6 on 2021-08-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_config_subpage_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='subpage_index',
            field=models.TextField(choices=[('button', 'Button (Default)'), ('list', 'List with expandable accordance')], default='button'),
        ),
    ]
