# Generated by Django 3.2.6 on 2021-09-02 12:08

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_config_subpage_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default tag', max_length=25)),
                ('pills_color', colorfield.fields.ColorField(default='#FF66AA', max_length=18)),
                ('font_color', colorfield.fields.ColorField(default='#FFFFFF', max_length=18)),
                ('description', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
