# Generated by Django 3.2.6 on 2021-09-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
