# Generated by Django 3.2.7 on 2021-09-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_tag_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='support_github_sponsors',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='support_kofi',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='support_message',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='support_patreon',
            field=models.URLField(blank=True),
        ),
    ]
