# Generated by Django 3.2.7 on 2021-09-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_profile_support_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='hide_email',
            field=models.BooleanField(default=False),
        ),
    ]
