# Generated by Django 3.2.8 on 2021-10-08 20:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_config_hide_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_light',
            field=models.ImageField(default='default_cover.png', upload_to='cover_pics_light', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'gif', 'jpg', 'jpeg', 'bmp', 'svg', 'webp'])]),
        ),
    ]
