# Generated by Django 3.2.8 on 2021-10-11 09:42

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='font_color',
            field=colorfield.fields.ColorField(blank=True, default='#FFFFFF', max_length=18),
        ),
        migrations.AlterField(
            model_name='tag',
            name='pills_color',
            field=colorfield.fields.ColorField(blank=True, default='#FF66AA', max_length=18),
        ),
    ]
