# Generated by Django 4.0.3 on 2022-04-08 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_config_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='language',
            field=models.TextField(choices=[('en', 'English (Default)'), ('th', 'Thai')], default='en-EN'),
        ),
    ]
