# Generated by Django 4.0.3 on 2022-04-08 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_alter_config_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='theme',
            field=models.TextField(choices=[('', 'Dark Mode (Default)'), ('light', 'Light Mode')], default='', null=True),
        ),
    ]
