# Generated by Django 4.0.3 on 2022-04-08 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_alter_config_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='theme',
            field=models.TextField(blank=True, choices=[('', 'Dark Mode (Default)'), ('light', 'Light Mode')], default=''),
        ),
    ]
