# Generated by Django 3.2.5 on 2021-08-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='note',
            field=models.TextField(default='Awesome release notes here!'),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='type',
            field=models.TextField(choices=[('pre-release', 'Pre-release'), ('stable', 'Stable')], default='stable'),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='version',
            field=models.CharField(default='', max_length=30),
        ),
    ]
