# Generated by Django 3.2.5 on 2021-08-02 18:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wiki', '0002_auto_20210802_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruleset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Awesome rulesets', max_length=20)),
                ('description', models.CharField(default='With awesome description', max_length=150)),
                ('cover_image', models.ImageField(default='default.jpeg', upload_to='profile_pics', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'gif', 'jpg', 'jpeg', 'bmp', 'svg'])])),
                ('content', models.TextField(default='and awesome content!')),
                ('open_source', models.BooleanField(default=True)),
                ('last_edited_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ruleset_page_creator', to=settings.AUTH_USER_MODEL)),
                ('last_edited_by', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ruleset_last_edited_by', to=settings.AUTH_USER_MODEL)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ruleset_ruleset_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
