# Generated by Django 3.2.5 on 2021-08-02 18:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_ruleset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruleset',
            name='cover_image',
            field=models.ImageField(default='default_wiki_cover.jpeg', upload_to='wiki_cover', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'gif', 'jpg', 'jpeg', 'bmp', 'svg'])]),
        ),
    ]
