# Generated by Django 3.2.5 on 2021-08-02 18:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_auto_20210802_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleset',
            name='icon',
            field=models.ImageField(default='default_icon.png', upload_to='rulesets_icon', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'gif', 'jpg', 'jpeg', 'bmp', 'svg'])]),
        ),
    ]
