# Generated by Django 3.2.5 on 2021-08-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0006_ruleset_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruleset',
            name='last_edited_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
