# Generated by Django 3.2.5 on 2021-08-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0008_auto_20210802_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruleset',
            name='creator',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='ruleset',
            name='last_edited_by',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='ruleset',
            name='owner',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
