# Generated by Django 3.2.5 on 2021-08-02 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0009_auto_20210802_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleset',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
