# Generated by Django 3.2.5 on 2021-08-02 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0010_ruleset_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleset',
            name='slug',
            field=models.SlugField(default='', max_length=20),
        ),
    ]
