# Generated by Django 3.2.5 on 2021-08-03 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0011_ruleset_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruleset',
            name='open_source',
        ),
    ]
