# Generated by Django 3.2.5 on 2021-08-03 20:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0012_remove_ruleset_open_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleset',
            name='logo',
            field=models.ImageField(default='default_logo.png', upload_to='rulesets_logo', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'gif', 'jpg', 'jpeg', 'bmp', 'svg'])]),
        ),
    ]
