# Generated by Django 3.2.5 on 2021-08-04 18:43

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0014_alter_ruleset_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruleset',
            name='content',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
