# Generated by Django 3.2.5 on 2021-08-04 19:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0015_alter_ruleset_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruleset',
            name='cover_image',
            field=models.ImageField(default='default_wiki_cover.jpeg', upload_to='wiki_cover', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'gif', 'jpg', 'jpeg', 'bmp', 'svg', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='ruleset',
            name='icon',
            field=models.ImageField(default='default_icon.png', upload_to='rulesets_icon', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'gif', 'jpg', 'jpeg', 'bmp', 'svg', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='ruleset',
            name='logo',
            field=models.ImageField(default='default_logo.jpeg', upload_to='rulesets_logo', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'gif', 'jpg', 'jpeg', 'bmp', 'svg', 'webp'])]),
        ),
    ]
