# Generated by Django 3.2.5 on 2021-08-04 21:22

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0016_auto_20210804_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='note',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
