# Generated by Django 3.2.5 on 2021-08-10 12:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0018_rename_github_link_ruleset_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
