# Generated by Django 3.2.5 on 2021-08-11 22:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0019_ruleset_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleset',
            name='opengraph_image',
            field=models.ImageField(default='default_wiki_cover.jpeg', upload_to='rulesets_opengraph_image', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'gif', 'jpg', 'jpeg', 'bmp', 'svg', 'webp'])]),
        ),
    ]
