# Generated by Django 3.2.6 on 2021-08-24 04:54

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0020_ruleset_opengraph_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomWiki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('last_edited_at', models.DateTimeField(auto_now=True)),
                ('creator', models.CharField(default='0', max_length=10)),
                ('last_edited_by', models.CharField(default='0', max_length=10)),
                ('content', mdeditor.fields.MDTextField()),
            ],
        ),
    ]
