# Generated by Django 3.2.6 on 2021-08-24 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0021_customwiki'),
    ]

    operations = [
        migrations.AddField(
            model_name='customwiki',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
