# Generated by Django 3.2.6 on 2021-08-25 18:19

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0022_customwiki_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruleset_id', models.CharField(default='', max_length=10)),
                ('title', models.CharField(default='', max_length=50)),
                ('slug', models.SlugField(default='', max_length=20)),
                ('content', mdeditor.fields.MDTextField()),
                ('last_edited_by', models.CharField(default='0', max_length=10)),
                ('last_edited_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
