# Generated by Django 3.2.6 on 2021-08-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0023_subpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subpage',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
