# Generated by Django 3.2.6 on 2021-08-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0025_alter_subpage_ruleset_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subpage',
            name='creator',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
