# Generated by Django 3.2.6 on 2021-08-28 12:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0026_subpage_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendBeatmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruleset_id', models.CharField(default='0', max_length=10)),
                ('user_id', models.CharField(default='0', max_length=10)),
                ('beatmap_id', models.IntegerField(default=75)),
                ('title', models.CharField(default='DISCO PRINCE', max_length=100)),
                ('artist', models.CharField(default='Kenji Ninuma', max_length=100)),
                ('source', models.CharField(default='', max_length=100)),
                ('approved', models.CharField(default='1', max_length=10)),
                ('difficultyrating', models.CharField(default='2.39774', max_length=10)),
                ('bpm', models.CharField(default='119.999', max_length=10)),
                ('beatmap_cover', models.ImageField(default='default_cover.png', upload_to='beatmap_cover', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'gif', 'jpg', 'jpeg', 'bmp', 'svg', 'webp'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
