# Generated by Django 3.2.6 on 2021-08-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0028_recommendbeatmap_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendbeatmap',
            name='version',
            field=models.CharField(default='Normal', max_length=50),
        ),
    ]
