# Generated by Django 3.2.6 on 2021-08-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0029_recommendbeatmap_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendbeatmap',
            name='beatmapset_id',
            field=models.IntegerField(default=1),
        ),
    ]
