# Generated by Django 3.2.6 on 2021-08-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0030_recommendbeatmap_beatmapset_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendbeatmap',
            name='url',
            field=models.URLField(default='https://osu.ppy.sh/beatmapsets/1#osu/75'),
        ),
    ]
