# Generated by Django 3.2.6 on 2021-08-28 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0031_recommendbeatmap_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendbeatmap',
            name='difficultyrating',
            field=models.FloatField(default='2.39774'),
        ),
    ]
