# Generated by Django 3.2.6 on 2021-08-29 08:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0032_alter_recommendbeatmap_difficultyrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendbeatmap',
            name='beatmap_thumbnail',
            field=models.ImageField(default='default_cover.png', upload_to='beatmap_thumbnail', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'gif', 'jpg', 'jpeg', 'bmp', 'svg', 'webp'])]),
        ),
    ]
