# Generated by Django 3.2.6 on 2021-08-29 09:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0033_recommendbeatmap_beatmap_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendbeatmap',
            name='creator',
            field=models.CharField(default='peppy', max_length=100),
        ),
        migrations.AlterField(
            model_name='recommendbeatmap',
            name='beatmap_cover',
            field=models.ImageField(default='default_beatmap_cover.jpeg', upload_to='beatmap_cover', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'gif', 'jpg', 'jpeg', 'bmp', 'svg', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='recommendbeatmap',
            name='beatmap_thumbnail',
            field=models.ImageField(default='default_beatmap_thumbnail.jpeg', upload_to='beatmap_thumbnail', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'gif', 'jpg', 'jpeg', 'bmp', 'svg', 'webp'])]),
        ),
    ]
