# Generated by Django 3.2.6 on 2021-08-29 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0034_auto_20210829_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleset',
            name='recommend_beatmap_cover',
            field=models.ImageField(default='default_recommend_beatmap_cover.png', upload_to='recommend_beatmap_cover', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'gif', 'jpg', 'jpeg', 'bmp', 'svg', 'webp'])]),
        ),
    ]
