# Generated by Django 3.2.6 on 2021-09-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0036_recommendbeatmap_owner_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendbeatmap',
            name='owner_seen',
            field=models.BooleanField(default=False),
        ),
    ]
