# Generated by Django 3.2.7 on 2021-09-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0037_recommendbeatmap_owner_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendbeatmap',
            name='source',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='recommendbeatmap',
            name='version',
            field=models.CharField(blank=True, default='Normal', max_length=50),
        ),
    ]
