# Generated by Django 3.2.7 on 2021-10-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0039_ruleset_github_download_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Rūrusetto action', max_length=200)),
                ('action_field', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.IntegerField(default=0)),
                ('time_start', models.DateTimeField(auto_now_add=True)),
                ('time_finish', models.DateTimeField(blank=True)),
                ('start_user', models.IntegerField(default=0)),
                ('log_file', models.FileField(upload_to='action_log')),
            ],
        ),
    ]
