# Generated by Django 3.2.7 on 2021-10-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0040_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='log_file',
        ),
        migrations.AddField(
            model_name='action',
            name='running_text',
            field=models.TextField(blank=True),
        ),
    ]
