# Generated by Django 3.2.7 on 2021-10-04 18:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0040_ruleset_dark_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruleset',
            name='dark_icon',
        ),
        migrations.AddField(
            model_name='ruleset',
            name='light_icon',
            field=models.ImageField(default='default_icon.png', upload_to='rulesets_icon_light', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'gif', 'jpg', 'jpeg', 'bmp', 'svg', 'webp'])]),
        ),
    ]
