# Generated by Django 3.2.7 on 2021-10-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0041_auto_20211003_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='time_finish',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
