# Generated by Django 3.2.7 on 2021-10-05 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0041_auto_20211004_2347'),
        ('wiki', '0042_alter_action_time_finish'),
    ]

    operations = [
    ]
