# Generated by Django 3.2.7 on 2021-10-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0044_rulesetstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulesetstatus',
            name='latest_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
