# Generated by Django 3.2.8 on 2021-10-06 04:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0045_alter_rulesetstatus_latest_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendbeatmap',
            name='beatmap_card',
            field=models.ImageField(default='default_beatmap_cover.jpeg', upload_to='beatmap_card', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'gif', 'jpg', 'jpeg', 'bmp', 'svg', 'webp'])]),
        ),
        migrations.AddField(
            model_name='recommendbeatmap',
            name='beatmap_list',
            field=models.ImageField(default='default_beatmap_thumbnail.jpeg', upload_to='beatmap_list', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'gif', 'jpg', 'jpeg', 'bmp', 'svg', 'webp'])]),
        ),
    ]
