# Generated by Django 3.2.8 on 2021-10-08 19:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0046_auto_20211006_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleset',
            name='cover_image_light',
            field=models.ImageField(default='default_wiki_cover.jpeg', upload_to='wiki_cover_light', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'gif', 'jpg', 'jpeg', 'bmp', 'svg', 'webp'])]),
        ),
    ]
