# Generated by Django 3.2.6 on 2021-10-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0050_alter_ruleset_custom_css'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleset',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subpage',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
