# Generated by Django 3.2.8 on 2021-10-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0051_auto_20211010_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendbeatmap',
            name='comment',
            field=models.TextField(blank=True, default=None),
        ),
    ]
