# Generated by Django 3.2.9 on 2021-11-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0052_alter_recommendbeatmap_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulesetstatus',
            name='pre_release',
            field=models.BooleanField(default=False),
        ),
    ]
