# Generated by Django 3.2.9 on 2021-12-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0053_rulesetstatus_pre_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleset',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
