# Generated by Django 3.2.9 on 2021-12-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0054_ruleset_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleset',
            name='direct_download_link',
            field=models.URLField(default=''),
        ),
    ]
