# Generated by Django 3.2.9 on 2021-12-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0055_ruleset_direct_download_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleset',
            name='can_download',
            field=models.BooleanField(default=False),
        ),
    ]
