# Generated by Django 3.2.9 on 2021-12-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0056_ruleset_can_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruleset',
            name='direct_download_link',
            field=models.URLField(blank=True, default=''),
        ),
    ]
