# Generated by Django 4.0.5 on 2022-06-13 05:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0057_alter_ruleset_direct_download_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendbeatmap',
            name='approved_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='recommendbeatmap',
            name='creator_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recommendbeatmap',
            name='favourite_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recommendbeatmap',
            name='genre_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recommendbeatmap',
            name='language_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recommendbeatmap',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='recommendbeatmap',
            name='playcount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recommendbeatmap',
            name='submit_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='recommendbeatmap',
            name='tags',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='recommendbeatmap',
            name='total_length',
            field=models.IntegerField(default=0),
        ),
    ]
